### ISSUE TITLE
Split bot logic into different tasks

### ISSUE THREAD

**Issue by GodLesZ** [kurotsukikaitou/PokeGo-Slave#13]
I've implemted a WIP inventory recycle and found it quite quite  hard to get an overview of  existing tasks.
Whats about splitting them into different task sub-files, included in the main logic?

Or  did  you have  some other thoughts about it?

**Comment by firanto** [comment]
Good idea. Initially, I didn't split them because I think this is just a project for learning material and never thought that anyone will contribute.

Any idea on how we should split them? Per function maybe?
- generateBarrier, calculateBearing, getRandomLocation into utils.js?
- getTrainerInformation into trainer.js?
- cleaningPokemon, incubateEggs into scheduledTask.js?
- collectPokeStop, catchPokemon, moveCharacter, heartbeat into heartbeat.js?
- verifyErrorRestart, restart into lifecycleUtils.js?

Any thought?

Anyway, to clarify things, in a nutshell, the task are:
- started
- get trainer info. This method do the following: get profile, get hatched eggs, get inventory and prepare those data. Initially, it also do the initial pokemon transfer and incubate eggs if incubator available. But I'm planning to move those two to separate task at the main (for transfer) and heartbeat (for incubating eggs).
- then start the main loop which calls heartbeat.

The heartbeat itself do the following:
- generate cellIds and call getMapObjects then parse them to each type (pokestop, gym, catchable, and nearby).
- If there are fort that we didn't collect yet, try collect items from it. We pause the loop while doing this (by setting doLoop to false).
- If there are no item collection task running, we continue to encounter catchable if any. Again, by pausing the loop.
- if there are no catchable target, then try to move the trainer avatar's location.

The reason I pause the loop whenever doing something (collect items, encounter catchable, transferring) was because I want to limit the bot into normal playing style as possible.

**Comment by GodLesZ** [comment]
As first I would try to use ES7 async feature to fully remove the `doLoop` .
After that, everything is just some sort of task which is executed on conditions.

Then maybe using `util.inherits()` for the different tasks.
Every task should be in a clearly named file because an newly dev can't know what is lifecycle-based and that only - more or less - just a utility.
I think about
- `catchPokemonTask.js` for the task and logic related to that
- `moveCharacterTask.js` for moving and also logic for extended stuff (other than random)

The `hearthbeat` is IMHO the loop itself, fetching/parsing the data and calling the tasks in general.

For `getTrainerInformation()` a util/ folder and some files should fit becausr its not an botting-task IMHO.

I will make some more thoughts

**Comment by firanto** [comment]
I think that's a good idea. Never thought about that.But isn't current Node (v6.3.1) doesn't support `async`/`await` yet?

About  `util.inherits()`... Isn't it's usage was discouraged by Node developers?

Anyway, all your point is quite interesting. I think that would makes the code easier to read. I'll think more about it.

Anyway... Niantic starting to crackdown bots (both users and provider alike). Still want to continue this project?

**Comment by GodLesZ** [comment]
Good morning (at least in GMT+1 😄 )!

Regarding your question - yes of cause!
I love Node.js and also game engineering, data analysis and proof-of-concept tasks.
I'm half the way down to split all functions up.
Also integrated https://www.npmjs.com/package/nodent for ES7 `async`/`await` features which are quite fun!

For the `util.inherits()` - you're right. Currently I use the `module.exports` object to expose a function which extends the `PokeGoWorker.prototype`. This is state of the art and will always work. So no `util.inherits()` here. ;)

Will release a PR today hopefully

**Comment by firanto** [comment]
I see. I'll keep this project until they issue CnD then.

Wow. Never thought there are implementations of `async`/`await` ready as third party. Nice to know that. :3

**Comment by GodLesZ** [comment]
Yes that's rly nice and works quite nice currently. ❤️ 

We'll see after I managed to bring the PR up

**Comment by GodLesZ** [comment]
Small update - I'm at 85% - 90% of splitting and `async` integration but won't finsh that today.

I'll push an PR tomorrow for review and testing.

**Comment by GodLesZ** [comment]
Well @kurotsukikaitou, I've got a C&D for the work in another project and can't finish this; officially..

Sorry for that

**Comment by firanto** [comment]
Hahaha. Figures. It's not before long that I might get that CnD too. I'll try to keep this repo as long as possible until receiving CnD. I'll close this issue then. :3
